config/routes.rb
Rails.application.routes.draw do
  resources :apply_classes
  devise_for :users
  resources :course_details
  resources :courses
  get 'home/index'

   get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  root 'home#index'

  get 'show_details' => 'courses#show_details'
  get 'signin' => 'home#signin'
  get 'signup' => 'home#signup'
  get 'all_courses' => 'home#all_courses'
  get 'about_us' => 'home#about_us'
  get 'contact_us' => 'home#contact_us'
  
  
  get 'list_apply_students' => 'apply_classes#list_apply_students'
 

end

app/models/course_detail.rb
class CourseDetail < ActiveRecord::Base
	
	belongs_to :a_course, class_name: 'Course', foreign_key: :course_id
end

app/controllers/course_details_controller.rb
class CourseDetailsController < ApplicationController
  before_action :set_course_detail, only: [:show, :edit, :update, :destroy]

  # GET /course_details
  # GET /course_details.json
  def index
    @course_details = CourseDetail.all
  end

  #  def show_details
  #   course_id = params[:id]
   
  #    @show_course_details= CourseDetail.joins("INNER JOIN courses ON courses.id = course_details.course_id
  #                 ").select('course_name,course_image,amount,tutor_name,tutor_info,course_level,category,course_description,course_duration,lecture_hours,course_curriculum,course_details.created_at').where(course_id: course_id)
  #   logger.info @show_course_details
   
  # end

  # GET /course_details/1
  # GET /course_details/1.json
  def show
  end

  # GET /course_details/new
  def new
    @course_detail = CourseDetail.new
  end

  # GET /course_details/1/edit
  def edit
  end

  # POST /course_details
  # POST /course_details.json
  def create
    @course_detail = CourseDetail.new(course_detail_params)

    respond_to do |format|
      if @course_detail.save
        format.html { redirect_to @course_detail, notice: 'Course detail was successfully created.' }
        format.json { render :show, status: :created, location: @course_detail }
      else
        format.html { render :new }
        format.json { render json: @course_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_details/1
  # PATCH/PUT /course_details/1.json
  def update
    respond_to do |format|
      if @course_detail.update(course_detail_params)
        format.html { redirect_to @course_detail, notice: 'Course detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @course_detail }
      else
        format.html { render :edit }
        format.json { render json: @course_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_details/1
  # DELETE /course_details/1.json
  def destroy
    @course_detail.destroy
    respond_to do |format|
      format.html { redirect_to course_details_url, notice: 'Course detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_detail
      @course_detail = CourseDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_detail_params
      params.require(:course_detail).permit(:course_id, :course_description, :course_duration, :lecture_hours, :course_curriculum)
    end
end

app/helpers/course_details_helper.rb
module CourseDetailsHelper
end

app/views/course_details/_form.html.erb
<%= simple_form_for(@course_detail) do |f| %>
    <%= f.error_notification %>

        <%= f.error_notification %>

 <div class="panel-body">
     <div class="position-center">

      <%= f.association :a_course, collection: Course.all, label_method: :course_name, value_method: :id, include_blank: true, label: "Course:", style:"width:90%;", :input_html => {:class => 'form-control dropdown dropdown-toggle', style:"width:90%;float:center;"} %>

      <%= f.input :course_description, required: true,input_html:{ class:"form-control",style:"width:90%;float:center;"} %>


      <%= f.label :course_duration, "course_duration" %>
      <br/>
      <%= f.text_field :course_duration, class:"form-control",style:"width:90%;" %>


 <%= f.label :lecture_hours, "lecture_hours" %>
      <br/>
      <%= f.text_field :lecture_hours, class:"form-control",style:"width:90%;" %>

       <%= f.label :course_curriculum, "course_curriculum" %>
      <br/>
      <%= f.text_field :course_curriculum, class:"form-control",style:"width:90%;" %>
     
     

       
      <br/>
      <br/>

    </div>

    <center>

    <%= f.submit "Submit", class: "btn btn-primary", style: "width:auto" %>&nbsp;&nbsp;&nbsp;&nbsp;

   

    </center>
    <% end %>

app/views/course_details/edit.html.erb
<h1>Editing Course Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @course_detail %> |
<%= link_to 'Back', course_details_path %>

app/views/course_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Course Details</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Course description</th>
      <th>Course duration</th>
      <th>Lecture hours</th>
      <th>Course curriculum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_details.each do |course_detail| %>
      <tr>
        <td><%= course_detail.course_id %></td>
        <td><%= course_detail.course_description %></td>
        <td><%= course_detail.course_duration %></td>
        <td><%= course_detail.lecture_hours %></td>
        <td><%= course_detail.course_curriculum %></td>
        <td><%= link_to 'Show', course_detail %></td>
        <td><%= link_to 'Edit', edit_course_detail_path(course_detail) %></td>
        <td><%= link_to 'Destroy', course_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course detail', new_course_detail_path %>

app/views/course_details/new.html.erb
<h1>New Course Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', course_details_path %>

app/views/course_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @course_detail.course_id %>
</p>

<p>
  <strong>Course description:</strong>
  <%= @course_detail.course_description %>
</p>

<p>
  <strong>Course duration:</strong>
  <%= @course_detail.course_duration %>
</p>

<p>
  <strong>Lecture hours:</strong>
  <%= @course_detail.lecture_hours %>
</p>

<p>
  <strong>Course curriculum:</strong>
  <%= @course_detail.course_curriculum %>
</p>

<%= link_to 'Edit', edit_course_detail_path(@course_detail) %> |
<%= link_to 'Back', course_details_path %>