config/routes.rb
Rails.application.routes.draw do
  resources :apply_classes
  devise_for :users
  resources :course_details
  resources :courses
  get 'home/index'

   get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  root 'home#index'

  get 'show_details' => 'courses#show_details'
  get 'signin' => 'home#signin'
  get 'signup' => 'home#signup'
  get 'all_courses' => 'home#all_courses'
  get 'about_us' => 'home#about_us'
  get 'contact_us' => 'home#contact_us'
  
  
  get 'list_apply_students' => 'apply_classes#list_apply_students'
 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

   validates :first_name,  allow_blank: false, :presence => { message: "Please provide First name"}
    validates :last_name,  allow_blank: false, :presence => { message: "Please provide Last name"}
                 
   validates_format_of :mobile_number,
      :with => /\(?[0-9]{3}\)?[0-9]{3}[0-9]{4}/,
      :message => "- Phone number must be 10 digits in 0xxxxxxxx format."
      
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :presence => { message: "Email is required"}



          devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  #        after_create :send_admin_mail
  # def send_admin_mail
  #   UserMailer.welcome_to_cybercity(self).deliver_now
  #   UserMailer.alert_cybercity(self).deliver_now  
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index 
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        
    
        format.html { redirect_to @user, notice: 'Signup successfully.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Users was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_index_url, notice: 'Users was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit()
    end

      def user_params
    params.require(:user).permit(:first_name, :last_name, :mobile_number, :gender, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :mobile_number %>
    <%= f.input :gender %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_index_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>No</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Mobile number</th>
      <th>Email</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	  <% count=1 %>
    <% @users.each do |user| %>
      <tr>
      	 <td><%= count %></td> 
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.mobile_number %></td>
         <td><%= user.email %></td>
        <td><%= user.gender %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
       <% count=count+1 %> 
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Users', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_index_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @user.mobile_number %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>