config/routes.rb
Rails.application.routes.draw do
  resources :apply_classes
  devise_for :users
  resources :course_details
  resources :courses
  get 'home/index'

   get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  root 'home#index'

  get 'show_details' => 'courses#show_details'
  get 'signin' => 'home#signin'
  get 'signup' => 'home#signup'
  get 'all_courses' => 'home#all_courses'
  get 'about_us' => 'home#about_us'
  get 'contact_us' => 'home#contact_us'
  
  
  get 'list_apply_students' => 'apply_classes#list_apply_students'
 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!,:only => [ :apply]

	 # layout "doc_patients",:only => [ :docs]
  def index
  	 @courses = Course.all
  end

  def all_courses
  	 @courses = Course.all
  end

   def apply
  	 @courses = Course.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb

<!doctype html>
<html lang="en">
  
  <body>
	<div class="page-banner">           			
        <div class="hvrbox">
           <img src="/assets/desktop.jpg" alt="Mountains" class="hvrbox-layer_bottom">
            <div class="hvrbox-layer_top">
                <div class="container">
                    <div class="overlay-text text-left">						
                        <h3>About Us</h3>
                        <nav aria-label="breadcrumb">
                          <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">About Us</li>
                          </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>	                     
    </div>

	<div class="about-us-2x">
		<div class="container">	
			<div class="row">	
				<div class="col-md-5">
					<div class="about-us-left">
						<h2>The CyberCity <span>Story</span></h2>
						<p><span>CyberCity School </span>started as an initiative by a group of software engineers in Ghana to create an environment or ecosytem of software developers.</p>
						<p>Our vision is to create a city full of game changers in futuristic technologies by impacting skills into people. A school specifically dedicated to teaching people how to code and be prepared for the future we are already witnessing.</p>
						<!-- <a href="#" class="btn-small"> Read More </a> -->
					</div>
				</div>
				<div class="col-md-6 offset-md-1">
					<div class="about-us-right with-video">
						<a href="" class="btn-circle video"><i class="fas fa-play"></i></a>
					</div>
				</div>
			</div>			
		</div>
	</div>

	<div class="about-us-2x only-description">
		<div class="container">	
			<div class="row">	
				<div class="col-md-6 padding-right">
					<div class="about-us-left container-out-left">						
						<h2>Why CyberCity <span>is the best?</span></h2>
						<p>CyberCity school provides hands-on approach to learning how to develop software solutions. Our Instructors are experts in a field of computer programming and have a track record of helping others to learn how to code in the easiest and faster way</p>
						<p>CyberCity ensures all students who undertake the courses are well vested for employment in any firm or create their own business.</p>
					</div>
				</div>
				<div class="col-md-6 padding-left">
					<div class="about-us-left container-out-right">
						<h2>CyberCity <span> courses </span></h2>
						<p>Our courses structured in a more dynamic approach teaching our students more software methodologies, modern programming languages and frameworks and international coding standards.</p>
						<p>We provide flexible course levels from beginners to advanced. Also, students who complete the course at every level is awarded a certificate just to recognize your skill achievement</p>
					</div>
				</div>
			</div>			
		</div>
	</div>

	<div class="about-us-2x about-differencs-2x">
		<div class="container">	
			<div class="row">	
				<div class="col-md-6 padding-right">
					<div class="about-us-left make-difference">
						<h2>What makes us <span>different?</span></h2>
						<p>We believe in ourselves to ensure students have the required skills in 12-weeks by employing a direct instructor-student practical apporoach in teaching coding or software development skills.</p>
						<p>Our course cost is the cheapest in the region whiles still maintaining quality in teaching and impacting skills.</p>
						
					</div>
				</div>
				<div class="col-md-6 padding-left">
					<div class="about-us-right container-out">
						<img src="/assets/about-1.png" alt="Mountains">
					</div>
				</div>
			</div>			
		</div>
	</div>

<!--     <div class="event-speakers best-instructor">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="title-middle">
						<h2>Our Best Instructors</h2>
						<p> The speaker bio is typically used in the programs at conferences, they may be used on the <br>  organization's website when promoting the event. </p>
					</div>	
				</div>

				<div class="col-md-12">
					<div class="ddoctors-slider">
						<div class="row">
							<div class="col-md-3">
								<div class="single-speaker">
									<div class="hvrbox">
										<img src="/assets/speaker-1.png" alt="slide 1" class="hvrbox-layer_bottom">
										<div class="hvrbox-layer_top hvrbox-text">
											<div class="hvrbox-text">							
				                               <ul>
													<li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
													<li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
													<li><a href="#"> <i class="fab fa-instagram"></i> </a></li>
												</ul>
											</div>
										</div>
									</div>
									<div class="speaker-details">						
										<h2>Eden Hezard</h2>					  
										<p>Designer, Marketo</p>
									</div>										  
									
								</div> 
							</div>
							<div class="col-md-3">
								<div class="single-speaker">
									<div class="hvrbox">
										<img src="/assets/speaker-1.png" alt="slide 1" class="hvrbox-layer_bottom">
										<div class="hvrbox-layer_top hvrbox-text">
											<div class="hvrbox-text">							
				                               <ul>
													<li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
													<li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
													<li><a href="#"> <i class="fab fa-instagram"></i> </a></li>
												</ul>
											</div>
										</div>
									</div>
									<div class="speaker-details">						
										<h2>Jim Brown</h2>					  
										<p>Marketer, Marketo</p>
									</div>										  
									
								</div> 
							</div>
							<div class="col-md-3">
								<div class="single-speaker">
									<div class="hvrbox">
										<img src="/assets/speaker-1.png" alt="slide 1" class="hvrbox-layer_bottom">
										<div class="hvrbox-layer_top hvrbox-text">
											<div class="hvrbox-text">							
				                               <ul>
													<li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
													<li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
													<li><a href="#"> <i class="fab fa-instagram"></i> </a></li>
												</ul>
											</div>
										</div>
									</div>
									<div class="speaker-details">						
										<h2>Thomas Silva</h2>					  
										<p>Developer, Marketo</p>
									</div>										  
									
								</div> 
							</div>
							<div class="col-md-3">
								<div class="single-speaker">
									<div class="hvrbox">
										<img src="/assets/speaker-1.png" alt="slide 1" class="hvrbox-layer_bottom">
										<div class="hvrbox-layer_top hvrbox-text">
											<div class="hvrbox-text">							
				                               <ul>
													<li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
													<li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
													<li><a href="#"> <i class="fab fa-instagram"></i> </a></li>
												</ul>
											</div>
										</div>
									</div>
									<div class="speaker-details">						
										<h2>Waytte Tylor</h2>					  
										<p>Designer, Marketo</p>
									</div>										  
									
								</div> 
							</div>
							
						</div>		
					</div>
				</div>	
			</div>
		</div>
	</div> -->   

	<div class="cta-1x">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="cta-content">
						<h3>Ready to Begin?</h3>
						<p>Find subjects you're passionate about by browsing our online course categories. Start <br> learning top courses from Industry Experts.</p>
						<%= link_to "Start Learning",apply_classes_path,:class=> "btn-small" %>
						<a  class="btn-small">Start Teaching</a>
					</div>
				</div>					
			</div>
		</div>
	</div>

  </body>
</html>       

app/views/home/all_courses.html.erb

	<!doctype html>
	<html lang="en">

	<body>
		


		<div class="main-banner course-list-banner">           			
			<div class="hvrbox">
				<!-- <img src="/assets/banner-1.png" alt="Mountains" class="hvrbox-layer_bottom"> -->
				 <img src="/assets/desktop.jpg" alt="Mountains" class="hvrbox-layer_bottom">
				<div class="hvrbox-layer_top">
					<div class="container">
						<div class="overlay-text text-center">						
							<h3><b>ALL</b> PRACTICAL COURSES!</h3>
							
						</div>
					</div>
				</div>
			</div>	                     
		</div>

		<div class="course-header-1x">
			<div class="container">
				<div class="row">
					
					<div class="col-md-12">
						

						<div class="course-grid-list">
							<div class="tab-content" id="myTabContent">
								<div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
									<div class="all-course-list">
										<% @courses.each do |course| %>
										<div class="media">
											<div class="media-left-image">
												<div class="hvrbox">
													<!-- <img src="/assets/1.jpg" alt="slide 1" class="hvrbox-layer_bottom"> -->
													<%= link_to image_tag (course.course_image),:class=> "hvrbox-layer_bottom" %>

													<div class="hvrbox-layer_top hvrbox-text">
														<div class="hvrbox-text">								<%= link_to "Preview Course", show_details_path(:id => course.id) %>
														</div>
													</div>
												</div>
											</div>
											<div class="media-body">
												<h2><%= link_to "#{course.course_name}", show_details_path(:id => course.id) %></h2>
												<h5>By <%= course.tutor_name %></h5>
												<h4>GHC<%= course.amount%> <del>GHC400</del></h4>
												

												<%= link_to "View Course", show_details_path(:id => course.id),:class=>"btn-bordered" %>
												<h3>
													<i class="fas fa-star"></i>
													<i class="fas fa-star"></i>
													<i class="fas fa-star"></i>
													<i class="fas fa-star"></i>
													<i class="fas fa-star"></i> (5)
													
												</h3>											
											</div>
										</div>
										<% end %>
										
									</div>
								</div>

								
							</div>
						</div>


					</div>
				</div>
			</div>
		</div>

		<div class="cta-1x">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="cta-content">
							<h3>Ready to Begin?</h3>
							<p>Find subjects you're passionate about by browsing our online course categories. Start <br> learning top courses with industry Experts.</p>
							<%= link_to "Start Learning",apply_classes_path,:class=> "btn-small" %>
						<a  class="btn-small">Start Teaching</a>
						</div>
					</div>					
				</div>
			</div>
		</div>

		
	</body>
	</html>       

app/views/home/apply.html.erb

<!doctype html>
<html lang="en">

<body>	
	<div class="page-banner">           			
		<div class="hvrbox">
			<img src="/assets/desktop.jpg" alt="Mountains" class="hvrbox-layer_bottom">
			<div class="hvrbox-layer_top">
				<div class="container">
					<div class="overlay-text text-left">						
						<h3>Apply - CyberCity Summer School 2019</h3>
						
					</div>
				</div>
			</div>
		</div>	                     
	</div>



	<div class="sign-in-1x">
		<div class="container">
			<div class="form-container">
				<div class="row">
					<div class="col-md-6">
						<div class="sign-in-form">
							<!-- <h3>Apply - CyberCity Summer School 2019</h3> -->
							<h3>Hello, <%= current_user.first_name  %> <br></h3>
							<form>
								<div class="row">	
								<!-- 	<div class="col-md-6">	
										<div class="single-input">
												<div class="form-group">
												<input type="text" class="form-control" placeholder="First Name" aria-label="Name">				    										    						    
											</div>
										</div>
									</div> -->	
										

										<div class="col-md-6">
										<div class="single-input">
												<label >Choose your Skill level</label>  
											<div class="form-group">							    
												<select  class="form-control">
													<option value="" selected="selected">Skill Level</option><option value="">Beginner</option><option value=""> Intermediary</option><option value="">Advanced</option>

												</select>							    
											</div>
										</div>
									</div> 		
									<div class="col-md-12">
										<div class="single-input">
											<label >Let us know briefly why you want to join the class and your expectations</label> 															  
											<div class="form-group">	

												   <textarea id = "myTextArea"
                  rows = "7"
                  cols = "120" placeholder="Let us know briefly why you want to join the class and your expectation"> </textarea>
										<!-- 	<%#= f.input :description, :label => false,placeholder: "Describe the kind of partnership you want?",as: :string,input_html: { class: "elementor-field elementor-size-sm  elementor-field-textual", row: "4" },validate: { presence: true, uniqueness: false } %> -->
										</div>						    
											</div>
										</div>
									<!-- </div> --> 

								<div class="col-md-12">
										
											<h3>Cost : GHc 300 for 12weeks<br>
											<h4>* To be qualified for the class, we require a 50% deposit. You can pay through mobile money  <a href=""> here!</a></h4></h3>	

									</div>

									<div class="col-md-12">
										<div class="sign-in-btn sign-up-btn">								<a href="#" class="btn-small">Complete Application</a>
	
										</div>								
									</div>
								</div>
							</form>
						</div>
					</div>
					<div class="col-md-6">
						<div class="sign-in-right sign-up-right">
							<a href="" class="btn-circle video"><i class="fas fa-play"></i></a>
						</div>
					</div>
				</div>													
			</div>
		</div>
	</div> 

	<div class="cta-1x">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="cta-content">
						<h3>Ready to Begin?</h3>
						<p>Find subjects you're passionate about by browsing our online course categories. Start <br> learning top courses from industry Experts.</p>
						<%= link_to "Start Learning",apply_classes_path,:class=> "btn-small" %>
						<a  class="btn-small">Start Teaching</a>

					</div>
				</div>					
			</div>
		</div>
	</div>


</body>
</html>       

app/views/home/index.html.erb

<!doctype html>
<html lang="en">

  <body>
 
	<div class="main-banner">           			
        <div class="hvrbox">
            <img src="/assets/banner_img.jpg" alt="Mountains" class="hvrbox-layer_bottom">
            <div class="hvrbox-layer_top">
                <div class="container">
                    <div class="overlay-text text-center">						
                        <h3>The Future Begins Here!</h3>
                        <p>Working collaboratively to ensure every student has a technical skill<br>to be prepared for the competitiveness of todays world of work.</p>
                   
                   <div class="slider-feature">
						
						<%= link_to "Enroll now!",apply_classes_path,:class=> "btn-small" %>

					</div>		
	
                    </div>
            	</div>
        	</div>
        </div>	                     
    </div>

    <div class="course-category-1x">
		<div class="container">
			<div class="row">				
				<div class="col-md-6">
					<div class="category-left left-image">
						<div class="hvrbox">
							<img src="/assets/1.jpg" alt="slide 1" class="hvrbox-layer_bottom">
							<div class="hvrbox-layer_top">
								<div class="hvrbox-text">
									
									<%= link_to "Introduction to Programming",all_courses_path %>
									<h5></h5>								
									<%= link_to "View Details",all_courses_path,:class=> "btn-small" %>
								</div>
							</div>
						</div>				  
					</div>
				</div>
				<div class="col-md-6">
					<div class="row">
						<div class="col-md-6">
							<div class="category-left right-image">
								<div class="hvrbox">
									<img src="/assets/web_dev.jpg" alt="slide 1" class="hvrbox-layer_bottom">
									<div class="hvrbox-layer_top hvrbox-text">
										<div class="hvrbox-text">
											
											<%= link_to "Web Development",all_courses_path %>
									<h5></h5>								
									<%= link_to "View Details",all_courses_path,:class=> "btn-small" %>
										</div>
									</div>
								</div>				  
							</div>						
						</div>
						<div class="col-md-6">
							<div class="category-left right-image">
								<div class="hvrbox">
									<img src="/assets/2.jpg" alt="slide 1" class="hvrbox-layer_bottom">
									<div class="hvrbox-layer_top hvrbox-text">
										<div class="hvrbox-text">
											
										<%= link_to "Mobile Application Development",all_courses_path %>
									<h5></h5>								
									<%= link_to "View Details",all_courses_path,:class=> "btn-small" %>
										</div>
									</div>
								</div>				  
							</div>						
						</div>
						<div class="col-md-6">
							<div class="category-left right-image">
								<div class="hvrbox">
									<img src="/assets/desktop.jpg" alt="slide 1" class="hvrbox-layer_bottom">
									<div class="hvrbox-layer_top hvrbox-text">
										<div class="hvrbox-text">
																		
											<%= link_to "Desktop Application Development",all_courses_path %>
									<h5></h5>								
									<%= link_to "View Details",all_courses_path,:class=> "btn-small" %>
										</div>
									</div>
								</div>				  
							</div>						
						</div>
						<div class="col-md-6">
							<div class="category-left right-image">
								<div class="hvrbox">
									<img src="/assets/software.jpg" alt="slide 1" class="hvrbox-layer_bottom">
									<div class="hvrbox-layer_top hvrbox-text">
										<div class="hvrbox-text">
										
											<%= link_to "Software Tools & Infrastructures",all_courses_path %>
									<h5></h5>								
									<%= link_to "View Details",all_courses_path,:class=> "btn-small" %>
										</div>
									</div>
								</div>				  
							</div>						
						</div>
					</div>
				</div>
				<div class="category-feature">
					<div class="col-md-12">
						<div class="row">
							<div class="col-md-4">
								<div class="single-feature">
									<img src="/assets/man-2.png" alt="slide 1">
									<h4>Expert Instructors</h4>
									<p>Our instructors are software engineers with a lot of experience with training and development beginners to achieve advanced level in coding. </p>
								</div>
							</div>
							<div class="col-md-4">
								<div class="single-feature">
									<img src="/assets/clock.png" alt="slide 1">
									<h4>Skills Development</h4>
									<p>We guarantee students to achieve a massive updgrade in skills after course. This we do due to our well prepared curriculum and our hands-on approach to the skill development. Everything is practical at Cybercity. </p>
								</div>
							</div>
							<div class="col-md-4">
								<div class="single-feature">
									<img src="/assets/pc.png" alt="slide 1">
									<h4>Certification</h4>
									<p>Students who complete the courses are awarded a professional certificate to certify their skill acquisition and give them advantage in securing a job or creating their own business </p>
								</div>
							</div>
							<div class="col-md-12">
								<div class="single-feature">
									
										<%= link_to "Get Started",apply_classes_path,:class=> "btn-small" %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="course-1x">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="title-middle">
						<h2>Cybercity Courses</h2>
					</div>
				</div>

				 
				  
				<div class="col-md-12">	
					<div class="all-course">
						<div class="row">
						<% @courses.each do |course| %>
						  <div class="col-md-3 tile web">
							<div class="single-course">
								<div class="hvrbox">
									<!-- <img src="/assets/1.jpg" alt="slide 1" class="hvrbox-layer_bottom"> -->
									<%= link_to image_tag (course.course_image),:class=> "hvrbox-layer_bottom" %>
									<div class="hvrbox-layer_top hvrbox-text">
										<div class="hvrbox-text">																	
											<!-- <a href="" class="btn-circle video"><i class="fas fa-play"></i></a> -->

											<%= link_to "Preview Course", show_details_path(:id => course.id) %>
											
										</div>
									</div>
								</div>
								<div class="single-course-content">
									<!-- <a href="course-single-one.html">Introduction to Programming</a> -->
									<%= link_to "#{course.course_name}", show_details_path(:id => course.id) %>
									<p>By <%= course.tutor_name %> <span><del>GHC400</del> <b>GHC<%= course.amount%></b></span></p>
									<h3>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i> (5)
										<!-- <span>Enroll: 128</span> -->
									</h3>
								</div>
							</div>
						  </div>
						  <% end %>
						  
						  
							<div class="col-md-12 text-center">
								<%= link_to "Enroll now!",apply_classes_path,:class=> "btn-small" %>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>

	<div class="achive-goals-1x">
		<div class="container">			
			<div class="col-md-12">
				<div class="title-middle">
					<h2>Requirements to be part of the class</h2>
					<p>CyberCity School is an open coding school for everyone ready to learn how to program and develop software. However, there are few things we require from potential students to be part of the school</p>
				</div>
			</div>

			<div class="col-md-12">
				<div class="row">
					<div class="col-md-4">
						<div class="single-goals">
							<img src="/assets/icon-1.png" alt="slide 1">
							<h4>Readiness to Learn</h4>
							<p>Potential students of code should be ready to learn and discipline. We require students to display a sense of motivation to learn and achieve success at the end of the course </p>
						</div>
					</div>
					<div class="col-md-4">
						<div class="single-goals">
							<img src="/assets/icon-2.png" alt="slide 1">
							<h4>50% payment before admission</h4>
							<p>Potential coders are required to pay a 50% deposit of fee before the 3-month course begins. This a refundable amount as long as student dont attend any of the class. </p>
						</div>
					</div>
					<div class="col-md-4">
						<div class="single-goals">
							<img src="/assets/icon-4.png" alt="slide 1">
							<h4>Have a personal Laptop</h4>
							<p>As a pistol is to a soldier, same way every coder should have a laptop. We therefore require potential students to own a laptop to aid in the practical sessions of development. If you dont own one, dont be left out. Just contact us so we make a preparation for you. </p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="learning-path-1x">
		<div class="container">
			<div class="col-md-12">
				<div class="title-middle">
					<h2>Get Ahead With Learning Paths</h2>
				</div>
			</div>

			<div class="col-md-12">
				<div class="learning-path">

					<div class="single-learning-path">
						<div class="hvrbox">
							<a href="#"><img src="/assets/1.jpg" alt="slide 1" class="hvrbox-layer_bottom"></a>
							<div class="hvrbox-layer_top hvrbox-text blue">
								<div class="hvrbox-text">
										
									<%= link_to "Become a Mobile App Developer",apply_classes_path %>						
								</div>
							</div>
						</div>
					</div>
					<div class="single-learning-path">
						<div class="hvrbox">
							<a href="#"><img src="/assets/2.jpg" alt="slide 1" class="hvrbox-layer_bottom"></a>
							<div class="hvrbox-layer_top hvrbox-text green">
								<div class="hvrbox-text">
										
									<%= link_to "Become a Web Developer",apply_classes_path %>						
								</div>
							</div>
						</div>
					</div>
					<div class="single-learning-path">
						<div class="hvrbox">
							<a href="#"><img src="/assets/3.jpg" alt="slide 1" class="hvrbox-layer_bottom"></a>
							<div class="hvrbox-layer_top hvrbox-text red">
								<div class="hvrbox-text">
										
										<%= link_to "Become a Software Engineer",apply_classes_path %>							
								</div>
							</div>
						</div>
					</div>
					<div class="single-learning-path">
						<div class="hvrbox">
							<a href="#"><img src="/assets/desktop.jpg" alt="slide 1" class="hvrbox-layer_bottom"></a>
							<div class="hvrbox-layer_top hvrbox-text yellow">
								<div class="hvrbox-text">
									

									<%= link_to "Create your own software product",apply_classes_path %>							
								</div>
							</div>
						</div>
					</div>
					<div class="single-learning-path">
						<div class="hvrbox">
							<a href="#"><img src="/assets/event-3.png" alt="slide 1" class="hvrbox-layer_bottom"></a>
							<div class="hvrbox-layer_top hvrbox-text">
								<div class="hvrbox-text">
										
									<%= link_to "Be part of the future",apply_classes_path %>						
								</div>
							</div>
						</div>
					</div>


				</div>
			</div>
		</div>
	</div>



	<div class="cta-1x">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="cta-content">
						<h3>Ready to Begin?</h3>
						<p>Find subjects you're passionate about by browsing our course categories. Start <br> learning with top courses from industry experts.</p>
						
						<%= link_to "Start Learning",apply_classes_path,:class=> "btn-small" %>
						<a  class="btn-small">Start Teaching</a>
						
						
					</div>
				</div>					
			</div>
		</div>
	</div>

	

   
	
  </body>
</html>       

app/views/home/signin.html.erb

<!doctype html>
<html lang="en">

  <body>
  

	<div class="page-banner">           			
        <div class="hvrbox">
            <img src="/assets/video-bg.png" alt="Mountains" class="hvrbox-layer_bottom">
            <div class="hvrbox-layer_top">
                <div class="container">
                    <div class="overlay-text text-left">						
                        <h3>Sign In</h3>
                        <nav aria-label="breadcrumb">
                          <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Sign In</li>
                          </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>	                     
    </div>
 
	<div class="sign-in-1x">
		<div class="container">
			<div class="form-container">
				<div class="row">
					<div class="col-md-4">
						<div class="sign-in-form">
							<h3>Sign In</h3>
							<form>
								<div class="row">
									<div class="col-md-12">	
										<div class="single-input">
											<i class="fas fa-envelope"></i>																  
											<div class="form-group">
												<input type="text" class="form-control" placeholder="Username or e-mail" aria-label="Name">				    										    						    
											</div>
										</div>
									</div>	
									<div class="col-md-12">
										<div class="single-input">
											<i class="fas fa-key"></i>																  
											<div class="form-group">							    
											    <input type="password" class="form-control" placeholder="Password">							    
											</div>
									  	</div>
									</div>  		
									<div class="col-md-12">
										<div class="sign-in-btn">																
											<span><a href="#">Forget Password?</a></span>
											<a href="#" class="btn-small"> Sign In </a>
											
											<h4>Don’t have an account? <a href="sign-up.html"> Create one here!</a></h4>	
										</div>								
									</div>
								</div>
							</form>
						</div>
					</div>
					<div class="col-md-7 offset-md-1">
						<div class="sign-in-right">
							<a href="" class="btn-circle video"><i class="fas fa-play"></i></a>
						</div>
					</div>													
				</div>
			</div>
		</div>
	</div> 

	<div class="cta-1x">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="cta-content">
						<h3>Ready to Begin?</h3>
						<p>Find subjects you're passionate about by browsing our online course categories. Start <br> learning top courses from Industry Experts.</p>
						<%= link_to "Start Learning",apply_path,:class=> "btn-small" %>
						<a  class="btn-small">Start Teaching</a>
					</div>
				</div>					
			</div>
		</div>
	</div>
	

	
  </body>
</html>       