config/routes.rb
Rails.application.routes.draw do
  resources :apply_classes
  devise_for :users
  resources :course_details
  resources :courses
  get 'home/index'

   get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  root 'home#index'

  get 'show_details' => 'courses#show_details'
  get 'signin' => 'home#signin'
  get 'signup' => 'home#signup'
  get 'all_courses' => 'home#all_courses'
  get 'about_us' => 'home#about_us'
  get 'contact_us' => 'home#contact_us'
  
  
  get 'list_apply_students' => 'apply_classes#list_apply_students'
 

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  #Show Course Details and display it in the show_details template
   def show_details
    @courses = Course.all
    # course_id=params[:id]
    # @course_details = CourseDetail.find_by(id: course_id)
    course_id = params[:id]  
     @show_course_details= CourseDetail.joins("INNER JOIN courses ON courses.id = course_details.course_id
                  ").select('course_name,course_image,amount,tutor_name,tutor_info,course_level,category,course_description,course_duration,lecture_hours,course_curriculum,course_details.created_at').where(course_id: course_id)
    logger.info @show_course_details.inspect
    logger.info "show course name: #{@show_course_details[0].course_name}"
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course_name, :course_image, :amount, :tutor_name, :tutor_info, :course_level, :category)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :course_name %><br>
    <%= f.text_field :course_name %>
  </div>
  <div class="field">
    <%= f.label :course_image %><br>
    <%= f.text_field :course_image %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :tutor_name %><br>
    <%= f.text_field :tutor_name %>
  </div>
  <div class="field">
    <%= f.label :tutor_info %><br>
    <%= f.text_field :tutor_info %>
  </div>
  <div class="field">
    <%= f.label :course_level %><br>
    <%= f.text_field :course_level %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table>
  <thead>
    <tr>
      <th>Course name</th>
      <th>Course image</th>
      <th>Amount</th>
      <th>Tutor name</th>
      <th>Tutor info</th>
      <th>Course level</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course_name %></td>
        <td><%= course.course_image %></td>
        <td><%= course.amount %></td>
        <td><%= course.tutor_name %></td>
        <td><%= course.tutor_info %></td>
        <td><%= course.course_level %></td>
        <td><%= course.category %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to  'Show more'.html_safe, show_details_path(:id => course.id) %>
            </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course name:</strong>
  <%= @course.course_name %>
</p>

<p>
  <strong>Course image:</strong>
  <%= @course.course_image %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @course.amount %>
</p>

<p>
  <strong>Tutor name:</strong>
  <%= @course.tutor_name %>
</p>

<p>
  <strong>Tutor info:</strong>
  <%= @course.tutor_info %>
</p>

<p>
  <strong>Course level:</strong>
  <%= @course.course_level %>
</p>

<p>
  <strong>Category:</strong>
  <%= @course.category %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/courses/show_details.html.erb

<!doctype html>
<html lang="en">

  <body>

	<div class="page-banner">           			
        <div class="hvrbox">
             <img src="/assets/desktop.jpg" alt="Mountains" class="hvrbox-layer_bottom">
            <div class="hvrbox-layer_top">
                <div class="container">
                    <div class="overlay-text text-left">						
                        <h3><%= @show_course_details[0].course_name %></h3>
                       
                    </div>
                </div>
            </div>
        </div>	                     
    </div>
    
    <div class="course-single-body">
		<div class="container">
			<div class="course-info-1x course-info-2x">	
				<div class="row">	
					<div class="col-md-4">
						<div class="course-info-left">
							<div class="media">
							 <!--  <img src="" alt="Image"> -->
							  <div class="media-body">
							  	<h3><%= @show_course_details[0].tutor_name %></h3>
								<p>Instructor</p>
							  </div>
							</div>						
						</div>
					</div>	
					<div class="col-md-3">
						<div class="course-info-middle">
							<p>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								<i class="fas fa-star"></i>
								&nbsp; 4.9 
							</p>
							<h4></h4>						
						</div>
					</div>
					<div class="col-md-2">
						<div class="course-info-left">
							<div class="media">
							  <div class="media-body">
							  	<h4>Course Duration</h4>
								<p><%= @show_course_details[0].course_duration %></p>
							  </div>
							</div>						
						</div>
					</div>
					<div class="col-md-3">
						<div class="course-info-right">
							<h3><del>GHC400</del>GHC <%= @show_course_details[0].amount %></h3>
							<%= link_to "Join Class",apply_classes_path,:class=> "btn-small" %>
							
						</div>
					</div>				

				</div>
			</div>
		</div>

		<div class="container">	
			<div class="course-details-1x">
				<div class="row">
					<div class="col-md-8">
						<div class="course-details-left">
							<div class="course-video">
								<a href="" class="btn-circle video"><i class="fas fa-play"></i></a>
								<h3>Preview Course</h3>
							</div>
						

							<div class="course-menu-nav">
								<ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
								  <li class="nav-item">
								    <a class="nav-link active" id="overview-tab" data-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true"> <i class="far fa-file-alt"></i>  Overview</a>
								  </li>
								  <li class="nav-item">
								    <a class="nav-link" id="curriculum-tab" data-toggle="tab" href="#curriculum" role="tab" aria-controls="curriculum" aria-selected="false"><i class="fas fa-cube"></i> Curriculum</a>
								  </li>
								  <li class="nav-item">
								    <a class="nav-link" id="instructor-tab" data-toggle="tab" href="#instructor" role="tab" aria-controls="instructor" aria-selected="false"><i class="far fa-user"></i> Instructor</a>
								  </li>
								  
								</ul>
								<div class="tab-content course-menu-tab" id="myTabContent">
								  <div class="tab-pane fade show active" id="overview" role="tabpanel" aria-labelledby="overview-tab">
								  	<div class="learning-system">
									  	<!-- <h4>What Will I Learn?</h4> -->
									  	<p><%= @show_course_details[0].course_description %></p>
										
									</div>
									
								  	<div class="price">
								  		<h5><del>GHC400</del><span>GHC300</span></h5>							  		
								  		<%= link_to "Join Class",apply_classes_path,:class=> "btn-small" %>
								  	</div>

								  </div>
								  <div class="tab-pane fade" id="curriculum" role="tabpanel" aria-labelledby="curriculum-tab">
									<div class="learning-system">
									  	<h4>What Will I Learn?</h4>
									  	<p><%= @show_course_details[0].course_description %></p>
										
									</div>
								
																  	
								  </div>
								  <div class="tab-pane fade" id="instructor" role="tabpanel" aria-labelledby="instructor-tab">
								  	<div class="blog-author instructor-profile">
										<div class="media">
										  <!-- <img src="/assets/speaker-1.png" alt="Generic placeholder image"> -->
										  <div class="media-body">
										    <h5><%= @show_course_details[0].tutor_name %></h5>
										    <p><%= @show_course_details[0].tutor_info %></p>							    
										  	<div class="social-link">
												<ul>
													<li class="facebook"><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>
													<li class="pinterest"><a href="#"> <i class="fab fa-pinterest"></i> </a></li>	
													<li class="instagram"><a href="#"> <i class="fab fa-instagram"></i> </a></li>											
													<li class="twitter"><a href="#"> <i class="fab fa-twitter"></i> </a></li>
												</ul>					
											</div>
										  </div>
										</div>							
									</div>
								  </div>
								
								</div>
							</div>

						</div>
					</div>				
					<div class="col-md-4">
						<div class="course-details-sidebar">
							<div class="course-feature">
								<h2>Course Features</h2>
								<ul>
									<!-- <li><i class="far fa-file"></i> Lectures <span> 7 </span></li> -->
									<li><i class="far fa-clock"></i> Duration <span> <%= @show_course_details[0].lecture_hours %> </span></li>
									<li><i class="far fa-user"></i> Students <span> 15 </span></li>
									<li><i class="fas fa-certificate"></i> Certificate  <span> Yes </span></li>
									<li><i class="far fa-lightbulb"></i> Skill  <span> <%= @show_course_details[0].course_level %>  </span></li>
									<li><i class="far fa-bookmark"></i> Category   <span> <%= @show_course_details[0].category %> </span></li>
								</ul>
							</div>
							<div class="footer-social-link">
								<h2>Share via</h2>
								<ul>
									<li><a href="#"> <i class="fab fa-facebook-f"></i> </a></li>	
									<li><a href="#"> <i class="fab fa-instagram"></i> </a></li>		
									<li><a href="#"> <i class="fab fa-twitter"></i> </a></li>
									<li><a href="#"> <i class="fab fa-google-plus-g"></i> </a></li>
								</ul>					
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="related-course-2x">
			<div class="container">
				<div class="col-md-12">
					<div class="row">
						<div class="title-left">
							<h2>Related Courses</h2>
						</div>
					</div>
				</div>

				<div class="related-course">
					<% @courses.each do |course| %>					
					<div class="single-course">
						<div class="hvrbox">
							
							<%= link_to image_tag (course.course_image),:class=> "hvrbox-layer_bottom" %>

							<div class="hvrbox-layer_top hvrbox-text">
								<div class="hvrbox-text">														<%= link_to "Preview Course", show_details_path(:id => course.id) %>
								</div>
							</div>
						</div>
						<div class="single-course-content">
							<%= link_to "#{course.course_name}", show_details_path(:id => course.id) %>
									<p>By <%= course.tutor_name %><span><del>GHC400</del> <b>GHC <%= course.amount%></b></span></p>
									<h3>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i> (5)
										
									</h3>
						</div>
					</div>
					<% end %>
				
				</div>
			</div>
		</div>

	</div>

	<div class="cta-1x">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="cta-content">
						<h3>Ready to Begin?</h3>
						<p>Find subjects you're passionate about by browsing our course categories. Start <br> learning with top courses with industry experts.</p>
						<%= link_to "Start Learning",apply_classes_path,:class=> "btn-small" %>
						<a  class="btn-small">Start Teaching</a>
					</div>
				</div>					
			</div>
		</div>
	</div>

    
	
  </body>
</html>       